### ISSUE TITLE
Error while pulling monotek/gcloud-mysql:14

### ISSUE THREAD

**Issue by sereinity** [monotek/gcloud-mysql#4]
When I (from my workstation, or a cluster) try to pull the tag `14` I get an error:

```bash
docker pull monotek/gcloud-mysql:14
14: Pulling from monotek/gcloud-mysql
c9b1b535fdd9: Pulling fs layer
154273e513cd: Pulling fs layer
933d69b35b6b: Pulling fs layer
a3f65b977c0a: Waiting
a7843b48aa70: Waiting
5bd1f4474bc7: Waiting
error pulling image configuration: unknown blob
```

But everything is fine if I try to pull `latest`

```bash
docker pull monotek/gcloud-mysql:latest
latest: Pulling from monotek/gcloud-mysql
cbdbe7a5bc2a: Already exists
bfd2de960b93: Pull complete
bbadd26eb264: Pull complete
2512e7430a45: Pull complete
6c20aff76af4: Pull complete
2c4023d5adc3: Pull complete
Digest: sha256:e236b122a8b7d390a273a11b82384576391cdf2ed658cf6ae971182430477892
Status: Downloaded newer image for monotek/gcloud-mysql:latest
docker.io/monotek/gcloud-mysql:latest
```

**Comment by monotek** [comment]
https://github.com/monotek/gcloud-mysql#docker-image ;-)

**Comment by sereinity** [comment]
That doesn't explain why it did work with `latest` (which I did just after) and I can reproduce the issue any time.

But thanks I didn't see that it moved to quay.

**Comment by Anticom** [comment]
FYI: [This](https://stackoverflow.com/a/63595329/966530) answer on SO sort of explains it or at least makes an assumption about what happened.
@monotek Maybe you can try to push it again to Docker Hub?

**Comment by monotek** [comment]
I was thinking about to remove the dockerhub repo completly anyway.

**Comment by monotek** [comment]
Dockerhub repo is deleted now.
